In [1]:
from utils import add_correlated_feature, make_superlearner, get_real_dataset



In [2]:
get_real_dataset('california')

(array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'])

In [3]:
get_real_dataset('diabetes')

(array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]], shape=(442, 10)),
 array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59.

In [4]:
get_real_dataset('concrete')

(array([[ 540. ,    0. ,    0. , ..., 1040. ,  676. ,   28. ],
        [ 540. ,    0. ,    0. , ..., 1055. ,  676. ,   28. ],
        [ 332.5,  142.5,    0. , ...,  932. ,  594. ,  270. ],
        ...,
        [ 148.5,  139.4,  108.6, ...,  892.4,  780. ,   28. ],
        [ 159.1,  186.7,    0. , ...,  989.6,  788.9,   28. ],
        [ 260.9,  100.5,   78.3, ...,  864.5,  761.5,   28. ]],
       shape=(1030, 8)),
 array([79.98611076, 61.88736576, 40.26953526, ..., 23.69660064,
        32.76803638, 32.40123514], shape=(1030,)),
 ['Cement (component 1)(kg in a m^3 mixture)',
  'Blast Furnace Slag (component 2)(kg in a m^3 mixture)',
  'Fly Ash (component 3)(kg in a m^3 mixture)',
  'Water  (component 4)(kg in a m^3 mixture)',
  'Superplasticizer (component 5)(kg in a m^3 mixture)',
  'Coarse Aggregate  (component 6)(kg in a m^3 mixture)',
  'Fine Aggregate (component 7)(kg in a m^3 mixture)',
  'Age (day)'])

In [5]:
get_real_dataset('wine-red')

(array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
        [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
        [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
        ...,
        [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
        [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
        [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]],
       shape=(1599, 11)),
 array([5, 5, 5, ..., 6, 5, 6], shape=(1599,)),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol'])

In [6]:
get_real_dataset('wine-white')

(array([[ 7.  ,  0.27,  0.36, ...,  3.  ,  0.45,  8.8 ],
        [ 6.3 ,  0.3 ,  0.34, ...,  3.3 ,  0.49,  9.5 ],
        [ 8.1 ,  0.28,  0.4 , ...,  3.26,  0.44, 10.1 ],
        ...,
        [ 6.5 ,  0.24,  0.19, ...,  2.99,  0.46,  9.4 ],
        [ 5.5 ,  0.29,  0.3 , ...,  3.34,  0.38, 12.8 ],
        [ 6.  ,  0.21,  0.38, ...,  3.26,  0.32, 11.8 ]], shape=(4898, 11)),
 array([6, 6, 6, ..., 6, 7, 6], shape=(4898,)),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol'])

In [7]:
get_real_dataset('energy')

(array([[9.800e-01, 5.145e+02, 2.940e+02, ..., 2.000e+00, 0.000e+00,
         0.000e+00],
        [9.800e-01, 5.145e+02, 2.940e+02, ..., 3.000e+00, 0.000e+00,
         0.000e+00],
        [9.800e-01, 5.145e+02, 2.940e+02, ..., 4.000e+00, 0.000e+00,
         0.000e+00],
        ...,
        [6.200e-01, 8.085e+02, 3.675e+02, ..., 3.000e+00, 4.000e-01,
         5.000e+00],
        [6.200e-01, 8.085e+02, 3.675e+02, ..., 4.000e+00, 4.000e-01,
         5.000e+00],
        [6.200e-01, 8.085e+02, 3.675e+02, ..., 5.000e+00, 4.000e-01,
         5.000e+00]], shape=(768, 8)),
 array([15.55 , 15.55 , 15.55 , 15.55 , 20.84 , 21.46 , 20.71 , 19.68 ,
        19.5  , 19.95 , 19.34 , 18.31 , 17.05 , 17.41 , 16.95 , 15.98 ,
        28.52 , 29.9  , 29.63 , 28.75 , 24.77 , 23.93 , 24.77 , 23.93 ,
         6.07 ,  6.05 ,  6.01 ,  6.04 ,  6.37 ,  6.4  ,  6.366,  6.4  ,
         6.85 ,  6.79 ,  6.77 ,  6.81 ,  7.18 ,  7.1  ,  7.1  ,  7.1  ,
        10.85 , 10.54 , 10.77 , 10.56 ,  8.6  ,  8.49 ,  8.45 ,  8.5 

In [8]:
import pandas as pd
import numpy as np

# Load raw data
col_names = ['id','diagnosis'] + [f'{feat}{stat}' for feat in
           ['radius','texture','perimeter','area','smoothness','compactness',
            'concavity','concave_points','symmetry','fractal_dimension']
           for stat in ['_mean','_se','_worst']]
df = pd.read_csv('data/wdbc.data', header=None, names=col_names)

# Drop ID
df = df.drop(columns=['id'])

# Convert diagnosis to binary
df['diagnosis'] = df['diagnosis'].map({'M':1, 'B':0})

X = df.drop(columns=['diagnosis']).values
y = df['diagnosis'].values

feature_names = list(df.drop(columns=['diagnosis']).columns)


In [9]:
get_real_dataset('wdbc')

(array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]], shape=(569, 30)),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
        0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
        0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,